fname = input("enter a female name")
Mname = input("enter a male name ")
obj = input("enter an object ")
street = input("enter a street name ")
vehicle = input("enter a vehicle ")
adj = input("enter an adjective ")
print(fname + " decided to move from her apartment on 5th")
print("to a condo on " + street + ". She called her friend " +Mname)
print("for help. However, they could not fit a(n) " + obj + " into")
print("the moving truck, so they had to rent a " + vehicle)
print("in order to move it!")
