fname = input("A female name:\n")
street = input("A street name:\n")
Mname = input("A male name:\n")
obj = input("An object:\n")
vehicle = input("A vehicle:\n")
adj = input("An adjective:\n")
print("----------")
print(fname + " decided to move from her apartment on 5th")
print("to a condo on " + street + ". She called her friend " +Mname)
print("for help. However, they could not fit " + obj + " into")
print("the moving truck, so they had to rent a " + adj + " " + vehicle)
print("in order to move it!")
